module.exports.descriptors = [
    'Oasi',
    'Resti antichi',
    'Good vibes',
    'Incanto',
    'Rilassante',
    'Cascata magnifica',
    'Silenziosa Natura',
    'Natura incontaminata',
    'Fauna selvatica',
    'Pineta lussurreggiante',
    'Grotta misteriosa',
    'Tripudio floreale',
    'Visione Urban',
    'Paesaggio marino',
    'Mare incantevole',
    'Cielo stellato',
    'Paesaggio collinare',
    'Gioiello Italiano'
]

module.exports.phSubjects = [
    'Monumento storico',
    'Paesino',
    'Canyon',
    'Cascata',
    'Lago',
    'Città abbandonata',
    'Zona industriale in disuso',
    'Punto panoramico',
    'Scavi archeologici',
    'Patrimonio Unesco',
    'Fiume',
    'Torrente',
    'Insenatura',
    'Baia',
    'Palazzi',
    'Parco nazionale',
    'Spiaggia',
    'Riserva naturalistica',
    'Parco naturale',
    'Scogliera',
    'Grotta'
]

module.exports.phCategories = [
    'Ritratti',
    'Artistica',
    'Glamour',
    'Naturalistica',
    'Paesaggistica',
    'Subacquea',
    'Urbana',
    'Macro',
    'Storytelling',
    'Still life',
    'Travel',
    'Documentaria',
    'Moda',
    'Nudo',
    'Astrofotografia',
    'Lunga esposizione',
    'Boudoir',
    'Matrimonio',
    'Narrative art',
    'Drone',
    'Food'
]

module.exports.phFocals = [
    '10',
    '15',
    '20',
    '25',
    '30',
    '35',
    '40',
    '50',
    '60',
    '70',
    '80',
    '90',
    '100',
    '110',
    '120',
    '130',
    '140',
    '150',
    '160',
    '170',
    '200+'
]